imageUploadSite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', include('upload.urls')),
    path('', RedirectView.as_view(url='/upload/', permanent=True))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

upload/urls.py
from django.urls import path
from django.conf.urls import include
from upload import views

urlpatterns = [path('', views.index, name='index')]

upload/models.py
from django.db import models
import uuid

# Create your models here.
class UploadedImage(models.Model):
    title = models.CharField(primary_key=True, max_length=100, help_text='Enter an image title')
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

upload/forms.py
from django import forms 
from .models import *
  
class UploadImageForm(forms.ModelForm): 
  
    class Meta: 
        model = UploadedImage 
        fields = ['image', 'title'] 

upload/views.py
from django.http import HttpResponse 
from django.shortcuts import render, redirect 
from upload.models import UploadedImage
from .forms import *

# Create your views here.
def index(request):
    alert_message = False
    if request.method == 'POST': 
        submitted_form = UploadImageForm(request.POST, request.FILES)

        if submitted_form.is_valid():
            submitted_form.save()
            alert_message = {
                'status': True,
                'message': 'Successfully saved the image'
            }
        else:
            alert_message = {
                'status': False,
                'message': 'Form data is invalid. Please check if your image / title is repeated'
            }
    
    form = UploadImageForm()
    context = {
        'alert_data': alert_message,
        'form': form,
        'images': UploadedImage.objects.all
    }
    return render(request, 'index.html', context=context)

upload/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Image Upload Site</title>{% endblock %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

</head>
<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

upload/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="text-center"><h1>Image Upload Page</h1></div>
        </div>
    </div>
    {% if alert_data %}
    <div class="row">
        <div style="margin:auto">
        <div class="alert {% if alert_data.status %} alert-success {% else %} alert-danger {% endif %}" role="alert">
            {{ alert_data.message }}
        </div></div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-12">
            <form method="post" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="row">
                <div class="file-upload">
                        <div class="image-upload-wrap">
                            <input class="file-upload-input" type='file' onchange="readURL(this);" name="image" accept="image/*" required="" id="id_image"/>
                            <div class="drag-text">
                                <i class="fas fa-download"></i>
                                <h4><strong>Choose a file</strong> or drag it here</h4>
                                <button class="btn btn-light" style="color:lightgray">Choose file</button>
                            </div>
                        </div>
                        <div class="file-upload-content">
                            <img class="file-upload-image" src="#" alt="your image" />
                            <div class="image-title-wrap">
                            <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                        </div>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="col-3"></div>
                    <div class="col-6">
                    <label for="id_title">Title:</label> <input placeholder="Player First Name" type="text" name="title" maxlength="100" required="" id="id_title">
                    <button class="submit-btn btn btn-primary" type="submit">Submit</button> 
                    </div>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <br/>
    <div class="row">
        
    {% for img in images %}
    
        <div class="col-md-4">
            <div> {{ img.title }}</div>
            <img class="img-thumbnail" src="{{img.image.url}}" alt="{{img.title}}" />
        </div>
    {% endfor %}
    </div>
</div>

<style>
    .submit-btn {
        margin-left: 10px;
    }
    .file-upload {
  background-color: #ffffff;
  width: 600px;
  margin: 0 auto;
  padding: 20px;
}

.file-upload-btn {
  width: 100%;
  margin: 0;
  color: #fff;
  background: rgb(192,213,218);
  border: none;
  padding: 10px;
  border-radius: 4px;
  border-bottom: 4px solid #15824B;
  transition: all .2s ease;
  outline: none;
  text-transform: uppercase;
  font-weight: 700;
}

.file-upload-btn:hover {
  background: #1AA059;
  color: #ffffff;
  transition: all .2s ease;
  cursor: pointer;
}

.file-upload-btn:active {
  border: 0;
  transition: all .2s ease;
}

.file-upload-content {
  display: none;
  text-align: center;
}

.file-upload-input {
  position: absolute;
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
  outline: none;
  opacity: 0;
  cursor: pointer;
}

.image-upload-wrap {
  margin-top: 20px;
  border: 4px dashed rgb(192,213,218);
  position: relative;
}

.image-dropping,
.image-upload-wrap:hover {
  background-color: rgb(192,213,218);
  border: 4px dashed #ffffff;
}

.image-title-wrap {
  padding: 0 15px 15px 15px;
  color: #222;
}

.drag-text {
  padding: 20px;
  text-align: center;
}

.drag-text h4 {
  color: rgb(31,54,73);
  font-size: 1em;
  padding-top: 20px;
  padding-bottom: 20px;
}

.file-upload-image {
  max-height: 200px;
  max-width: 200px;
  margin: auto;
  padding: 20px;
}

.remove-image {
  width: 200px;
  margin: 0;
  color: #fff;
  background: #cd4535;
  border: none;
  padding: 10px;
  border-radius: 4px;
  border-bottom: 4px solid #b02818;
  transition: all .2s ease;
  outline: none;
  text-transform: uppercase;
  font-weight: 700;
}

.remove-image:hover {
  background: #c13b2a;
  color: #ffffff;
  transition: all .2s ease;
  cursor: pointer;
}

.remove-image:active {
  border: 0;
  transition: all .2s ease;
}
</style>

<script>
    function readURL(input) {
  if (input.files && input.files[0]) {

    var reader = new FileReader();

    reader.onload = function(e) {
      $('.image-upload-wrap').hide();

      $('.file-upload-image').attr('src', e.target.result);
      $('.file-upload-content').show();

      $('.image-title').html(input.files[0].name);
    };

    reader.readAsDataURL(input.files[0]);

  } else {
    removeUpload();
  }
}

function removeUpload() {
  $('.file-upload-input').replaceWith($('.file-upload-input').clone());
  $('.file-upload-content').hide();
  $('.image-upload-wrap').show();
}
$('.image-upload-wrap').bind('dragover', function () {
		$('.image-upload-wrap').addClass('image-dropping');
	});
	$('.image-upload-wrap').bind('dragleave', function () {
		$('.image-upload-wrap').removeClass('image-dropping');
});

</script>

{% endblock %}